import Head from 'next/head'
import styles from '../../styles/About.module.css'
import Layout2 from '../../components/Layout2'

const Page2 = () => {
  return (
    <div className={styles.about}>
      <Head>
        <title>Page 2 | Book List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello from Page 2</h1>
      <p className={styles.content}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae vitae voluptatibus, suscipit deleniti eum, sequi exercitationem ipsa ullam fuga porro ducimus. Quisquam suscipit in error voluptate eaque. Placeat, magnam voluptas.</p>
      <p className={styles.content}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae vitae voluptatibus, suscipit deleniti eum, sequi exercitationem ipsa ullam fuga porro ducimus. Quisquam suscipit in error voluptate eaque. Placeat, magnam voluptas.</p>
      <p className={styles.content}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae vitae voluptatibus, suscipit deleniti eum, sequi exercitationem ipsa ullam fuga porro ducimus. Quisquam suscipit in error voluptate eaque. Placeat, magnam voluptas.</p>
    </div>
  )
}

Page2.Layout = Layout2

export default Page2