import Head from 'next/head'
import styles from '../../styles/About.module.css'

const About = () => {
  return (
    <div className={styles.about}>
      <Head>
        <title>About | Book List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello from About Page</h1>
      <p className={styles.content}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae vitae voluptatibus, suscipit deleniti eum, sequi exercitationem ipsa ullam fuga porro ducimus. Quisquam suscipit in error voluptate eaque. Placeat, magnam voluptas.</p>
      <p className={styles.content}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae vitae voluptatibus, suscipit deleniti eum, sequi exercitationem ipsa ullam fuga porro ducimus. Quisquam suscipit in error voluptate eaque. Placeat, magnam voluptas.</p>
      <p className={styles.content}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae vitae voluptatibus, suscipit deleniti eum, sequi exercitationem ipsa ullam fuga porro ducimus. Quisquam suscipit in error voluptate eaque. Placeat, magnam voluptas.</p>
    </div>
  )
}

export default About