import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ pictures }) {


  return (
    <div className={styles.container}>
      <Head>
        <title>Book List Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Example json api
        </h1>
        <div id="gallery" className={styles.gallery}>
          {pictures.map(picture => {
            let myImage = `https://picsum.photos/id/${picture.id}/172/129.jpg`

            return (
              <figure key={picture.id}>
                <Image alt="some image" src={myImage} layout="fill" />
                <figcaption>
                  {picture.author}
                </figcaption>
              </figure>
          )})}
        </div>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {

  const res = await fetch('https://picsum.photos/v2/list?limit=15')
  const data = await res.json()

  if (!data) {
    return {
      notFound: true
    }
  }

  return {
    props: { pictures: data }
  }
}